# Generated by Django 6.0 on 2025-12-09 10:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_media', models.CharField(choices=[('Livre', 'Livre'), ('DVD', 'DVD'), ('CD', 'CD'), ('Jeu', 'Jeu de Plateau')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('artiste', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_media', models.CharField(choices=[('Livre', 'Livre'), ('DVD', 'DVD'), ('CD', 'CD'), ('Jeu', 'Jeu de Plateau')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('realisateur', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('createur', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_media', models.CharField(choices=[('Livre', 'Livre'), ('DVD', 'DVD'), ('CD', 'CD'), ('Jeu', 'Jeu de Plateau')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('auteur', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(default=django.utils.timezone.now)),
                ('retourne', models.BooleanField(default=False)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliotheque.emprunteur')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliotheque.livre')),
            ],
        ),
    ]
