# Generated by Django 6.0 on 2025-12-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_alter_emprunt_date_emprunt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprunt',
            name='media',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='cd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts_cd', to='bibliotheque.cd'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='dvd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts_dvd', to='bibliotheque.dvd'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='jeu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts_jeu', to='bibliotheque.jeudeplateau'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='livre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emprunts_livre', to='bibliotheque.livre'),
        ),
    ]
