# Generated by Django 6.0 on 2025-12-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0003_remove_emprunt_media_emprunt_cd_emprunt_dvd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cd',
            name='type_media',
        ),
        migrations.RemoveField(
            model_name='dvd',
            name='type_media',
        ),
        migrations.RemoveField(
            model_name='livre',
            name='type_media',
        ),
    ]
